version: "3"
services:
  gitlab-lint-react:
    image: gitlab-lint-react:local
    build: .
    tty: true
    stdin_open: true
    environment:
      REACT_APP_API_URL: ./api/v1
      # REACT_APP_API_URL: http://localhost:8888/api/v1
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
